version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    environment:
      FLASK_ENV: development
    networks:
      - appbridge

  web:
    container_name: web
    build:
      context: .
      dockerfile: web.Dockerfile
    links:
      - backend
    ports:
      - "80:3000"
    volumes:
      - ./web:/app
    environment:
      - NODE_ENV=development
    networks:
      - appbridge

  redis:
    image: "redis:alpine"
    networks:
      - appbridge

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root12345
      MYSQL_USER: local_user
      MYSQL_PASSWORD: root12345
      MYSQL_DATABASE: local_database
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - appbridge

networks:
  appbridge:
    driver: bridge