version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    environment:
      FLASK_ENV: development
    networks:
      - appbridge

  web:
    container_name: web
    build:
      context: .
      dockerfile: web.Dockerfile
    links:
      - backend
    ports:
      - '80:3000'
    environment:
      - NODE_ENV=development
    networks:
      - appbridge

  redis:
    image: "redis:alpine"
    networks:
      - appbridge

networks:
  appbridge:
    driver: bridge