version: '3'
services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    environment:
      FLASK_ENV: development

  web:
    container_name: web
    build:
      context: .
      dockerfile: web.Dockerfile
    volumes:
      - './web:/app'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development

  redis:
    image: "redis:alpine"